version: "3.9"

# Declaro los servicios a utilizar
services:

  # Servicio de base de datos
  postgres:
    image: postgres:alpine
    ports:
      - "5435:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    
    
  # Servicio de backend
  backend:
    build: .
    container_name: admin-services
    env_file:
      - .env
    restart: on-failure
    ports:
      - 8000:8000

